In [3]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier

In [10]:
df=pd.read_csv("data/Iris_setosa_versicolor.csv",index_col="Id")

print(df.shape)
df

(100, 5)


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id                                                                            
1              5.1           3.5            1.4           0.2      Iris-setosa
2              4.9           3.0            1.4           0.2      Iris-setosa
3              4.7           3.2            1.3           0.2      Iris-setosa
4              4.6           3.1            1.5           0.2      Iris-setosa
5              5.0           3.6            1.4           0.2      Iris-setosa
..             ...           ...            ...           ...              ...
96             5.7           3.0            4.2           1.2  Iris-versicolor
97             5.7           2.9            4.2           1.3  Iris-versicolor
98             6.2           2.9            4.3           1.3  Iris-versicolor
99             5.1           2.5            3.0           1.1  Iris-versicolor
100            5.7           2.8            4.1           1.3  Iris-versicolor

[100 rows x 5 columns]

In [11]:
#전처리
df["Species"]=df.Species.map({"Iris-setosa":0, "Iris-versicolor":1})
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        0
2              4.9           3.0            1.4           0.2        0
3              4.7           3.2            1.3           0.2        0
4              4.6           3.1            1.5           0.2        0
5              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
96             5.7           3.0            4.2           1.2        1
97             5.7           2.9            4.2           1.3        1
98             6.2           2.9            4.3           1.3        1
99             5.1           2.5            3.0           1.1        1
100            5.7           2.8            4.1           1.3        1

[100 rows x 5 columns]

In [24]:
X=np.array(df.iloc[:,:4])
y=np.array(df['Species'])
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [25]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
#트레이닝세트와 테스트세트로 데이터 구분
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

print("X_train 크기:", X_train.shape)
print("y_train 크기:", y_train.shape)
print("X_test 크기:", X_test.shape)
print("y_test 크기:", y_test.shape)

X_train 크기: (70, 4)
y_train 크기: (70,)
X_test 크기: (30, 4)
y_test 크기: (30,)


In [27]:
from sklearn.tree import DecisionTreeClassifier

tree=DecisionTreeClassifier(random_state=0) #max미지정
tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [28]:
#모델성능평가
temp_y_pred = tree.predict(X_test)
#training 값을 X_test에서 넣음
print('예측값\n', temp_y_pred)
print('실제값\n', y_test)

예측값
 [0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1]
실제값
 [0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1]


In [29]:
#정확도 계산
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

temp_acc = accuracy_score(y_test, temp_y_pred)
#y_test와 temp_y_pred로 예측한 값을 적용하여 temp_acc를 추출함

print('정확도: ', format(temp_acc))

정확도:  1.0


In [30]:
#오차행렬(Confusion Matrix)
print(confusion_matrix(y_test, temp_y_pred))

[[15  0]
 [ 0 15]]


In [31]:
from sklearn.metrics import precision_score, recall_score, f1_score

print('accuracy :', accuracy_score(y_test, temp_y_pred))
print('precision :', precision_score(y_test, temp_y_pred))
print('recall :', recall_score(y_test, temp_y_pred))
print('f1 :', f1_score(y_test, temp_y_pred))

accuracy : 1.0
precision : 1.0
recall : 1.0
f1 : 1.0


In [32]:
#모델 성능
print(classification_report(y_test,tree.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [33]:
#실습해보자
tree.predict([[5.1, 4.0, 1.4, 0.2]])

array([0], dtype=int64)